# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dde52c1c520fc198722e129c03ef0c45fc41384d89c83de7277a34cee1ee3db6e9354295648a00c5b2326da7fbb17ae76ed45248c47294ceb4371fe8c14e72aa

test:
  secret_key_base: 8363b28af44b7259d1f7426ad6941f1281befecf80ae164f900afb1e47e80a059caa480a90da8eba3b059811877371b9e345a7975ceed27d014e211aa90efe66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token:  <%= ENV["SECRET_TOKEN"] %>
